// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeulDNYViC51vdNBSso1TxA4SeQQ45zU',
    appId: '1:150057979453:web:6803fb27cd87fcccf7a454',
    messagingSenderId: '150057979453',
    projectId: 'chatonce-a2127',
    authDomain: 'chatonce-a2127.firebaseapp.com',
    storageBucket: 'chatonce-a2127.firebasestorage.app',
    measurementId: 'G-YLK77YRQ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOYfDlF_JLNE-LcGIowjQ0r24bKLT9MI',
    appId: '1:150057979453:android:12d1716f7f770bb3f7a454',
    messagingSenderId: '150057979453',
    projectId: 'chatonce-a2127',
    storageBucket: 'chatonce-a2127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7nMREzu2aaYb3tYQ23toWrJe5UzxmE0',
    appId: '1:150057979453:ios:132ab0e5de539c74f7a454',
    messagingSenderId: '150057979453',
    projectId: 'chatonce-a2127',
    storageBucket: 'chatonce-a2127.firebasestorage.app',
    iosBundleId: 'com.once.chatonce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7nMREzu2aaYb3tYQ23toWrJe5UzxmE0',
    appId: '1:150057979453:ios:132ab0e5de539c74f7a454',
    messagingSenderId: '150057979453',
    projectId: 'chatonce-a2127',
    storageBucket: 'chatonce-a2127.firebasestorage.app',
    iosBundleId: 'com.once.chatonce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjeulDNYViC51vdNBSso1TxA4SeQQ45zU',
    appId: '1:150057979453:web:2a11a10a408e68b9f7a454',
    messagingSenderId: '150057979453',
    projectId: 'chatonce-a2127',
    authDomain: 'chatonce-a2127.firebaseapp.com',
    storageBucket: 'chatonce-a2127.firebasestorage.app',
    measurementId: 'G-YFXHZC8JK3',
  );
}
